export {CommodityManagement} from './CommodityManagement/CommodityManagement.page';
export {FinalPurchase} from './FinalPurchase/FinalPurchase.page';
export {Home} from './Home/Home.page';
export {InventoryManagement} from './InventoryManagement/InventoryManagement.page';
export {LoginPanelManager} from './LoginPanelManager/LoginPanelManager.page';
export {MacPayment} from './MacPayment/MacPayment.page';
export {OrdersManager} from './OrdersManager/OrdersManager.page';
export {PaymentResult} from './PaymentResult/PaymentResult.page';
export {ProductsList} from './ProductsList/ProductsList.page';
export {Purchase} from './Purchase/Purchase.page';
export {NotFound} from './NotFound/NotFound.page'
export {Basket} from './Basket/Basket.component'